### ISSUE TITLE
fatal error: sys/timex.h: No such file or directory

### ISSUE THREAD

**Issue by ryandesign** [twekkel/htpdate#46]
As [reported to MacPorts](https://trac.macports.org/ticket/73183) by @barracuda156, htpdate 2.0.1 fails to build on Mac OS X 10.5:

```
htpdate.c:48:10: fatal error: sys/timex.h: No such file or directory
   48 | #include <sys/timex.h>
      |          ^~~~~~~~~~~~~
```

The sys/timex.h header first appeared in macOS 10.13.

**Comment by twekkel** [comment]
Mac OS X Leopard version 10.5 was released in 2007 and EOL since 2011... or am I missing something?

**Comment by barracuda156** [comment]
Well, it is the last macOS to support ppc64, but in any case, the same issue affects macOS up to 10.12, it is not specific to 10.5.

**Comment by twekkel** [comment]
Right... if somebody has a workaround/fix, please create a PR.

**Comment by barracuda156** [comment]
Conditionally excluding the header is easy, but there are a few places where timex stuff is used. 
https://github.com/twekkel/htpdate/blob/1e57b0513e85bda71a026a9f84c5d4bddaf56dd2/htpdate.c#L556-L564
https://github.com/twekkel/htpdate/blob/1e57b0513e85bda71a026a9f84c5d4bddaf56dd2/htpdate.c#L613-L674
https://github.com/twekkel/htpdate/blob/1e57b0513e85bda71a026a9f84c5d4bddaf56dd2/htpdate.c#L1047

@ryandesign Ryan, do you know if there is a suitable fallback?

**Comment by ryandesign** [comment]
I have no knowledge of this.
